spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    properties:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com.example.abstractionizer.login.session1/db/rmdb/mappers/*Mapper.xml

redis:
  port: 6379
  host: localhost
  pool:
    maxIdle: 8
    minIdle: localhost
    maxActive: -1
    maxWait: 30000

email:
  address: "java.application.testing2021@gmail.com"
  password: "testing2021"
